//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cademeumedicoEntities : DbContext
    {
        public cademeumedicoEntities()
            : base("name=cademeumedicoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<bannerspublicitarios> bannerspublicitarios { get; set; }
        public DbSet<cidades> cidades { get; set; }
        public DbSet<especialidades> especialidades { get; set; }
        public DbSet<medicos> medicos { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
